name: Generate snake animation and update GitHub stats

on:
  schedule:
    - cron: "*/5 * * * *" # execute every 5 minutes

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate_snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_github_stats:
    needs: generate_snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKE }}
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=tijcesar&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false&token=${{ secrets.GH_TOKE }}"
          echo '![](./stats.svg)' > README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKE }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKE }}@github.com/${{ github.repository }}
          git add README.md stats.svg
          git commit -m "Update GitHub Stats"
          git push origin HEAD:main
